name: deploy

on:
  push:
    branches:
      - master

jobs:
  caprover:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u team-501-the-powerknights --password-stdin
          docker build -t ghcr.io/team-501-the-powerknights/website .
          docker push ghcr.io/team-501-the-powerknights/website
      - run: docker run caprover/cli-caprover:v2.1.1 caprover deploy --caproverUrl https://api.mattglei.ch --caproverPassword ${{ secrets.CAPROVER_PASSWORD }} --caproverApp powerknights-site --imageName ghcr.io/team-501-the-powerknights/website
