name: Publish
on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1.3.2
        with:
          channel: 'beta'
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter build web
      - name: Commit changes
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "Publishing Bot"
          git checkout pubspec.lock
          git checkout gh-pages
          sh replace.sh
          rm -rf README.md
          touch README.md
          TZ=America/New_York date
          date >> README.md
          git add .
          git commit -m "🚀 Publish Latest Changes"
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'gh-pages'
